### ISSUE TITLE
如何監聽畫面上元件的事件?

### ISSUE THREAD

**Issue by godchadigo** [773596523/FormDesigner#1]
請問被拖到畫面上的控件，我想要偵測他被點擊的事件，我應該在哪去做事件監聽呢?
![image](https://github.com/LemonNoCry/FormDesigner/assets/19208239/e276f549-54d2-4f3b-87e1-c45e3614d192)

**Comment by LemonNoCry** [comment]
暫時不支持

**Comment by godchadigo** [comment]
好的
